### ISSUE TITLE
Error thrown when using Rx gate

### ISSUE THREAD

**Issue by HyperSphereStudio** [redfx-quantum/strange#96]
Rx gate(Single Qubit Gate): 
new Complex[][]{
                    {new Complex(getCos(rads / 2)), new Complex(0, -getSin(rads / 2))},
                    {new Complex(0, getSin(rads / 2)), new Complex(getCos(rads / 2))}}

When I use this gate, I sometimes get the following error when using values between 0 and 2Pi:
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at org.redfx.strange.Result.measureSystem(Result.java:137)
	at org.redfx.strange.local.SimpleQuantumExecutionEnvironment.runProgram(SimpleQuantumExecutionEnvironment.java:127)`

Perhaps its a misimplementation of the gate on my end, but this same error is occuring for other rotation gates I have been trying to add

Circuit: 1 Bit, Rx(0, PI)

**Comment by johanvos** [comment]
Thanks for reporting this.
Can you share a sample that reproduces this crash?
If it happens sometimes, it means that the sum of the probabilities doesn't add up to 100%. The code in `Result.java` has been changed since 0.0.21-SNAPSHOT, but looking at the code in the previous release, line 137 is where the index is incremented in case the total probability is lower than a random number.
Hence, it sounds to me that your gate is wrong, but I don't exclude it is an error in Strange.
In any case, Strange should provide testing for gates (i.e. is it a reversible gate?).

**Comment by HyperSphereStudio** [comment]
Just double checked the code and realized that it was an error in implementing the gate. I accidentally had the function "getSin" divide the theta by two aswell. Works fine after fixing this, it was an error on my part. This explains why other gates that used the "getSin" were also failing.
